// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 3.21.12
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `common.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:common.PhoneInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PhoneInfo {
    // message fields
    // @@protoc_insertion_point(field:common.PhoneInfo.instance_id)
    pub instance_id: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:common.PhoneInfo.connectivity_lifetime_id)
    pub connectivity_lifetime_id: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:common.PhoneInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PhoneInfo {
    fn default() -> &'a PhoneInfo {
        <PhoneInfo as ::protobuf::Message>::default_instance()
    }
}

impl PhoneInfo {
    pub fn new() -> PhoneInfo {
        ::std::default::Default::default()
    }

    // optional string instance_id = 1;

    pub fn instance_id(&self) -> &str {
        match self.instance_id.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_instance_id(&mut self) {
        self.instance_id = ::std::option::Option::None;
    }

    pub fn has_instance_id(&self) -> bool {
        self.instance_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_instance_id(&mut self, v: ::std::string::String) {
        self.instance_id = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_instance_id(&mut self) -> &mut ::std::string::String {
        if self.instance_id.is_none() {
            self.instance_id = ::std::option::Option::Some(::std::string::String::new());
        }
        self.instance_id.as_mut().unwrap()
    }

    // Take field
    pub fn take_instance_id(&mut self) -> ::std::string::String {
        self.instance_id.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string connectivity_lifetime_id = 2;

    pub fn connectivity_lifetime_id(&self) -> &str {
        match self.connectivity_lifetime_id.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_connectivity_lifetime_id(&mut self) {
        self.connectivity_lifetime_id = ::std::option::Option::None;
    }

    pub fn has_connectivity_lifetime_id(&self) -> bool {
        self.connectivity_lifetime_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_connectivity_lifetime_id(&mut self, v: ::std::string::String) {
        self.connectivity_lifetime_id = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_connectivity_lifetime_id(&mut self) -> &mut ::std::string::String {
        if self.connectivity_lifetime_id.is_none() {
            self.connectivity_lifetime_id = ::std::option::Option::Some(::std::string::String::new());
        }
        self.connectivity_lifetime_id.as_mut().unwrap()
    }

    // Take field
    pub fn take_connectivity_lifetime_id(&mut self) -> ::std::string::String {
        self.connectivity_lifetime_id.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "instance_id",
            |m: &PhoneInfo| { &m.instance_id },
            |m: &mut PhoneInfo| { &mut m.instance_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "connectivity_lifetime_id",
            |m: &PhoneInfo| { &m.connectivity_lifetime_id },
            |m: &mut PhoneInfo| { &mut m.connectivity_lifetime_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PhoneInfo>(
            "PhoneInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PhoneInfo {
    const NAME: &'static str = "PhoneInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.instance_id = ::std::option::Option::Some(is.read_string()?);
                },
                18 => {
                    self.connectivity_lifetime_id = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.instance_id.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(v) = self.connectivity_lifetime_id.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.instance_id.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.connectivity_lifetime_id.as_ref() {
            os.write_string(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PhoneInfo {
        PhoneInfo::new()
    }

    fn clear(&mut self) {
        self.instance_id = ::std::option::Option::None;
        self.connectivity_lifetime_id = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PhoneInfo {
        static instance: PhoneInfo = PhoneInfo {
            instance_id: ::std::option::Option::None,
            connectivity_lifetime_id: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PhoneInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PhoneInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PhoneInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PhoneInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:common.HeadUnitInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct HeadUnitInfo {
    // message fields
    // @@protoc_insertion_point(field:common.HeadUnitInfo.make)
    pub make: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:common.HeadUnitInfo.model)
    pub model: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:common.HeadUnitInfo.year)
    pub year: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:common.HeadUnitInfo.vehicle_id)
    pub vehicle_id: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:common.HeadUnitInfo.head_unit_make)
    pub head_unit_make: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:common.HeadUnitInfo.head_unit_model)
    pub head_unit_model: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:common.HeadUnitInfo.head_unit_software_build)
    pub head_unit_software_build: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:common.HeadUnitInfo.head_unit_software_version)
    pub head_unit_software_version: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:common.HeadUnitInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a HeadUnitInfo {
    fn default() -> &'a HeadUnitInfo {
        <HeadUnitInfo as ::protobuf::Message>::default_instance()
    }
}

impl HeadUnitInfo {
    pub fn new() -> HeadUnitInfo {
        ::std::default::Default::default()
    }

    // optional string make = 1;

    pub fn make(&self) -> &str {
        match self.make.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_make(&mut self) {
        self.make = ::std::option::Option::None;
    }

    pub fn has_make(&self) -> bool {
        self.make.is_some()
    }

    // Param is passed by value, moved
    pub fn set_make(&mut self, v: ::std::string::String) {
        self.make = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_make(&mut self) -> &mut ::std::string::String {
        if self.make.is_none() {
            self.make = ::std::option::Option::Some(::std::string::String::new());
        }
        self.make.as_mut().unwrap()
    }

    // Take field
    pub fn take_make(&mut self) -> ::std::string::String {
        self.make.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string model = 2;

    pub fn model(&self) -> &str {
        match self.model.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_model(&mut self) {
        self.model = ::std::option::Option::None;
    }

    pub fn has_model(&self) -> bool {
        self.model.is_some()
    }

    // Param is passed by value, moved
    pub fn set_model(&mut self, v: ::std::string::String) {
        self.model = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_model(&mut self) -> &mut ::std::string::String {
        if self.model.is_none() {
            self.model = ::std::option::Option::Some(::std::string::String::new());
        }
        self.model.as_mut().unwrap()
    }

    // Take field
    pub fn take_model(&mut self) -> ::std::string::String {
        self.model.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string year = 3;

    pub fn year(&self) -> &str {
        match self.year.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_year(&mut self) {
        self.year = ::std::option::Option::None;
    }

    pub fn has_year(&self) -> bool {
        self.year.is_some()
    }

    // Param is passed by value, moved
    pub fn set_year(&mut self, v: ::std::string::String) {
        self.year = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_year(&mut self) -> &mut ::std::string::String {
        if self.year.is_none() {
            self.year = ::std::option::Option::Some(::std::string::String::new());
        }
        self.year.as_mut().unwrap()
    }

    // Take field
    pub fn take_year(&mut self) -> ::std::string::String {
        self.year.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string vehicle_id = 4;

    pub fn vehicle_id(&self) -> &str {
        match self.vehicle_id.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_vehicle_id(&mut self) {
        self.vehicle_id = ::std::option::Option::None;
    }

    pub fn has_vehicle_id(&self) -> bool {
        self.vehicle_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_vehicle_id(&mut self, v: ::std::string::String) {
        self.vehicle_id = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_vehicle_id(&mut self) -> &mut ::std::string::String {
        if self.vehicle_id.is_none() {
            self.vehicle_id = ::std::option::Option::Some(::std::string::String::new());
        }
        self.vehicle_id.as_mut().unwrap()
    }

    // Take field
    pub fn take_vehicle_id(&mut self) -> ::std::string::String {
        self.vehicle_id.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string head_unit_make = 5;

    pub fn head_unit_make(&self) -> &str {
        match self.head_unit_make.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_head_unit_make(&mut self) {
        self.head_unit_make = ::std::option::Option::None;
    }

    pub fn has_head_unit_make(&self) -> bool {
        self.head_unit_make.is_some()
    }

    // Param is passed by value, moved
    pub fn set_head_unit_make(&mut self, v: ::std::string::String) {
        self.head_unit_make = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_head_unit_make(&mut self) -> &mut ::std::string::String {
        if self.head_unit_make.is_none() {
            self.head_unit_make = ::std::option::Option::Some(::std::string::String::new());
        }
        self.head_unit_make.as_mut().unwrap()
    }

    // Take field
    pub fn take_head_unit_make(&mut self) -> ::std::string::String {
        self.head_unit_make.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string head_unit_model = 6;

    pub fn head_unit_model(&self) -> &str {
        match self.head_unit_model.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_head_unit_model(&mut self) {
        self.head_unit_model = ::std::option::Option::None;
    }

    pub fn has_head_unit_model(&self) -> bool {
        self.head_unit_model.is_some()
    }

    // Param is passed by value, moved
    pub fn set_head_unit_model(&mut self, v: ::std::string::String) {
        self.head_unit_model = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_head_unit_model(&mut self) -> &mut ::std::string::String {
        if self.head_unit_model.is_none() {
            self.head_unit_model = ::std::option::Option::Some(::std::string::String::new());
        }
        self.head_unit_model.as_mut().unwrap()
    }

    // Take field
    pub fn take_head_unit_model(&mut self) -> ::std::string::String {
        self.head_unit_model.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string head_unit_software_build = 7;

    pub fn head_unit_software_build(&self) -> &str {
        match self.head_unit_software_build.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_head_unit_software_build(&mut self) {
        self.head_unit_software_build = ::std::option::Option::None;
    }

    pub fn has_head_unit_software_build(&self) -> bool {
        self.head_unit_software_build.is_some()
    }

    // Param is passed by value, moved
    pub fn set_head_unit_software_build(&mut self, v: ::std::string::String) {
        self.head_unit_software_build = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_head_unit_software_build(&mut self) -> &mut ::std::string::String {
        if self.head_unit_software_build.is_none() {
            self.head_unit_software_build = ::std::option::Option::Some(::std::string::String::new());
        }
        self.head_unit_software_build.as_mut().unwrap()
    }

    // Take field
    pub fn take_head_unit_software_build(&mut self) -> ::std::string::String {
        self.head_unit_software_build.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string head_unit_software_version = 8;

    pub fn head_unit_software_version(&self) -> &str {
        match self.head_unit_software_version.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_head_unit_software_version(&mut self) {
        self.head_unit_software_version = ::std::option::Option::None;
    }

    pub fn has_head_unit_software_version(&self) -> bool {
        self.head_unit_software_version.is_some()
    }

    // Param is passed by value, moved
    pub fn set_head_unit_software_version(&mut self, v: ::std::string::String) {
        self.head_unit_software_version = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_head_unit_software_version(&mut self) -> &mut ::std::string::String {
        if self.head_unit_software_version.is_none() {
            self.head_unit_software_version = ::std::option::Option::Some(::std::string::String::new());
        }
        self.head_unit_software_version.as_mut().unwrap()
    }

    // Take field
    pub fn take_head_unit_software_version(&mut self) -> ::std::string::String {
        self.head_unit_software_version.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "make",
            |m: &HeadUnitInfo| { &m.make },
            |m: &mut HeadUnitInfo| { &mut m.make },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "model",
            |m: &HeadUnitInfo| { &m.model },
            |m: &mut HeadUnitInfo| { &mut m.model },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "year",
            |m: &HeadUnitInfo| { &m.year },
            |m: &mut HeadUnitInfo| { &mut m.year },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "vehicle_id",
            |m: &HeadUnitInfo| { &m.vehicle_id },
            |m: &mut HeadUnitInfo| { &mut m.vehicle_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "head_unit_make",
            |m: &HeadUnitInfo| { &m.head_unit_make },
            |m: &mut HeadUnitInfo| { &mut m.head_unit_make },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "head_unit_model",
            |m: &HeadUnitInfo| { &m.head_unit_model },
            |m: &mut HeadUnitInfo| { &mut m.head_unit_model },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "head_unit_software_build",
            |m: &HeadUnitInfo| { &m.head_unit_software_build },
            |m: &mut HeadUnitInfo| { &mut m.head_unit_software_build },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "head_unit_software_version",
            |m: &HeadUnitInfo| { &m.head_unit_software_version },
            |m: &mut HeadUnitInfo| { &mut m.head_unit_software_version },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<HeadUnitInfo>(
            "HeadUnitInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for HeadUnitInfo {
    const NAME: &'static str = "HeadUnitInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.make = ::std::option::Option::Some(is.read_string()?);
                },
                18 => {
                    self.model = ::std::option::Option::Some(is.read_string()?);
                },
                26 => {
                    self.year = ::std::option::Option::Some(is.read_string()?);
                },
                34 => {
                    self.vehicle_id = ::std::option::Option::Some(is.read_string()?);
                },
                42 => {
                    self.head_unit_make = ::std::option::Option::Some(is.read_string()?);
                },
                50 => {
                    self.head_unit_model = ::std::option::Option::Some(is.read_string()?);
                },
                58 => {
                    self.head_unit_software_build = ::std::option::Option::Some(is.read_string()?);
                },
                66 => {
                    self.head_unit_software_version = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.make.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(v) = self.model.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.year.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        if let Some(v) = self.vehicle_id.as_ref() {
            my_size += ::protobuf::rt::string_size(4, &v);
        }
        if let Some(v) = self.head_unit_make.as_ref() {
            my_size += ::protobuf::rt::string_size(5, &v);
        }
        if let Some(v) = self.head_unit_model.as_ref() {
            my_size += ::protobuf::rt::string_size(6, &v);
        }
        if let Some(v) = self.head_unit_software_build.as_ref() {
            my_size += ::protobuf::rt::string_size(7, &v);
        }
        if let Some(v) = self.head_unit_software_version.as_ref() {
            my_size += ::protobuf::rt::string_size(8, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.make.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.model.as_ref() {
            os.write_string(2, v)?;
        }
        if let Some(v) = self.year.as_ref() {
            os.write_string(3, v)?;
        }
        if let Some(v) = self.vehicle_id.as_ref() {
            os.write_string(4, v)?;
        }
        if let Some(v) = self.head_unit_make.as_ref() {
            os.write_string(5, v)?;
        }
        if let Some(v) = self.head_unit_model.as_ref() {
            os.write_string(6, v)?;
        }
        if let Some(v) = self.head_unit_software_build.as_ref() {
            os.write_string(7, v)?;
        }
        if let Some(v) = self.head_unit_software_version.as_ref() {
            os.write_string(8, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> HeadUnitInfo {
        HeadUnitInfo::new()
    }

    fn clear(&mut self) {
        self.make = ::std::option::Option::None;
        self.model = ::std::option::Option::None;
        self.year = ::std::option::Option::None;
        self.vehicle_id = ::std::option::Option::None;
        self.head_unit_make = ::std::option::Option::None;
        self.head_unit_model = ::std::option::Option::None;
        self.head_unit_software_build = ::std::option::Option::None;
        self.head_unit_software_version = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static HeadUnitInfo {
        static instance: HeadUnitInfo = HeadUnitInfo {
            make: ::std::option::Option::None,
            model: ::std::option::Option::None,
            year: ::std::option::Option::None,
            vehicle_id: ::std::option::Option::None,
            head_unit_make: ::std::option::Option::None,
            head_unit_model: ::std::option::Option::None,
            head_unit_software_build: ::std::option::Option::None,
            head_unit_software_version: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for HeadUnitInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("HeadUnitInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for HeadUnitInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HeadUnitInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0ccommon.proto\x12\x06common\"f\n\tPhoneInfo\x12\x1f\n\x0binstance_i\
    d\x18\x01\x20\x01(\tR\ninstanceId\x128\n\x18connectivity_lifetime_id\x18\
    \x02\x20\x01(\tR\x16connectivityLifetimeId\"\xaf\x02\n\x0cHeadUnitInfo\
    \x12\x12\n\x04make\x18\x01\x20\x01(\tR\x04make\x12\x14\n\x05model\x18\
    \x02\x20\x01(\tR\x05model\x12\x12\n\x04year\x18\x03\x20\x01(\tR\x04year\
    \x12\x1d\n\nvehicle_id\x18\x04\x20\x01(\tR\tvehicleId\x12$\n\x0ehead_uni\
    t_make\x18\x05\x20\x01(\tR\x0cheadUnitMake\x12&\n\x0fhead_unit_model\x18\
    \x06\x20\x01(\tR\rheadUnitModel\x127\n\x18head_unit_software_build\x18\
    \x07\x20\x01(\tR\x15headUnitSoftwareBuild\x12;\n\x1ahead_unit_software_v\
    ersion\x18\x08\x20\x01(\tR\x17headUnitSoftwareVersionB-\n#com.google.and\
    roid.projection.protoB\x06Common\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(PhoneInfo::generated_message_descriptor_data());
            messages.push(HeadUnitInfo::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
